environment:
  node_pre_gyp_accessKeyId:
    secure: BB4XzOLXvG+XMmXyCVwqaFF/hKJnYvjIACQMD423QvY=
  node_pre_gyp_secretAccessKey:
    secure: BFW25HQ0Jdq8IpysC59Y2mh1J9IsXwWB+FTElHVSYVl5xDwwZPHrXwctZQLzKrw9
  matrix:
    - nodejs_version: 4
      platform: x64
    - nodejs_version: 4
      platform: x86
    - nodejs_version: 6
      platform: x64
    - nodejs_version: 6
      platform: x86
    - nodejs_version: 8
      platform: x64
    - nodejs_version: 8
      platform: x86
    - nodejs_version: 9
      platform: x64
    - nodejs_version: 9
      platform: x86


os: Visual Studio 2015

install:
  - scripts\build-appveyor.bat

skip_tags: true
build: OFF
test: OFF
deploy: OFF
